apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Values.service.name }} 
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }} 
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }} 
        visualize: "true"
    spec:
      tolerations:
      - operator: "Exists"
      volumes:
      - name: docker-sock
        hostPath:
          path: "/var/run/docker.sock"
      imagePullSecrets:
        - name: nexusregistry 
      containers:
      - name: {{ .Values.service.name }} 
        image: {{ .Values.image.repository }} 
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        volumeMounts:
        - name: docker-sock
          mountPath: "/var/run/docker.sock"
        env:
        - name: ALERT_LOGIC_KEY
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: alertlogic.registration-key
        - name: ALERT_LOGIC_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: alert-logic-host
        resources: 
{{ toYaml .Values.resources | indent 12 }}
